### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by 17Skye17** [ju-chen/Efficient-Prompt#2]
Hi,
Nice work! May I know when will you release the code? Thank you.

**Comment by ju-chen** [comment]
The code will be made available in the near future. While recently we are waiting for review comments. In addition, we also need time to clean up the code to make it easy to reproduce. Thank you all for your understanding and patience.

**Comment by 17Skye17** [comment]
Thank you for your reply, good luck 👍
