### ISSUE TITLE
Just want to know when will the code be released ?

### ISSUE THREAD

**Issue by Palette25** [ju-chen/Efficient-Prompt#3]

**Comment by ju-chen** [comment]
The code will be made available in the near future. While recently we are waiting for review comments. In addition, we also need time to clean up the code to make it easy to reproduce. Thank you all for your understanding and patience.

**Comment by dreamerlin** [comment]
Will the code be released recently?

**Comment by xiao2mo** [comment]
Hi, there. Will the code be released recently?

**Comment by ju-chen** [comment]
Thanks for your patience and understanding. The core code is now available, and codes on more datasets are coming soon.
