### ISSUE TITLE
Query regarding the testing setup for Action Localization

### ISSUE THREAD

**Issue by sauradip** [ju-chen/Efficient-Prompt#4]
In the supplementary file, it has been written that for Action Localization , in ActivityNet dataset, each snippet consists of 768 frames ? This is extremely dense feature , because normal benchmarked approaches use 8 or 16 frames ! Is this claim correct ? If yes, can you share this feature atleast if not the code ? 
![Screenshot from 2021-12-17 01-46-38](https://user-images.githubusercontent.com/23197350/146475205-2536d6df-46f6-48cf-9183-dc74cbfdcc98.png)

**Comment by ju-chen** [comment]
Sorry for misleading of the "snippet".

Normal benchmarked approaches combine 8 or 16 frames to form a "snippet", which is similar to down-sampling the video fps by 8 or 16 times. Then they divide (rescale) the video into video clips of equal snippet numbers.

Our work (following AFSD) uses the original video fps, then divides the video into video clips of 768 frames. And we call the video clip as the "snippet".

We will make this clear in the next version. Thanks.

**Comment by sauradip** [comment]
Thanks for your clarification !

Also I have a additional question regarding the Action Localization setup : so in the paper it is written that a off-the-shelf action detector is used ! So is it the pretrained weights that the authors have released is used for the detectors ?

**Comment by ju-chen** [comment]
Since we use the CLIP pre-trained features instead of two-stream I3D features, we train the proposal detector from scratch. By the way, congratulations on your work at ECCV2022.

**Comment by sauradip** [comment]
Thanks for the response ! And also congratulations to you too for ECCV 2022 !
