### ISSUE TITLE
About K700 openset split

### ISSUE THREAD

**Issue by dreamerlin** [ju-chen/Efficient-Prompt#6]
Thanks for your wonderful work~ I want to know the details about your K700 openset split. 

Is it right that videos of 400 classes in the original K700 training split are used for openset training, and videos of the other 300 classes in original K700 val splits are used for openset validation?

Or you directly gather all videos of K700 in both training and val list, and pick 400 classes for training and use the left videos of 300 classes for validation?

**Comment by gurkirt** [comment]
I have the same question. 
Can you please publish the lists for these two sets of classes?

**Comment by ju-chen** [comment]
Sorry for the late reply. 
We use videos of 400 classes in the original K700 training split for training, and videos of the other 300 classes in original K700 val splits for evaluation.

**Comment by gurkirt** [comment]
But which 400? First 400 or random 400?

**Comment by ju-chen** [comment]
Please see ./datasplits/Open-set Action Recognition/K700/
