### ISSUE TITLE
about feature extract

### ISSUE THREAD

**Issue by duckburgerhill** [ju-chen/Efficient-Prompt#8]
Thank you for your excellent work！But I have some problems about the feature extract. 
Could you please upload the code about the feature extract?  I want to reproduce the work on my own dataset.
Thank a lot !

**Comment by ju-chen** [comment]
The code for feature extraction has been updated. Thank you for the patience.

**Comment by HappyPiepie** [comment]
Thank you for your excellent work！But I have some problems about the feature extract. Could you please upload the code about a video to  feature and how to get  Text description from a video clip? I just want to test my own video,
